type=item
items=bow
texture=chupik_bow.png
texture.bow_pulling_0=chupik_bow_pulling_0.png
texture.bow_pulling_1=chupik_bow_pulling_1.png
texture.bow_pulling_2=chupik_bow_pulling_2.png
nbt.display.Name=ipattern:*Погибельник*|*Чупик*|*Погибельник*|*Чупик*|*chupik_bow*
